#!/bin/sh
# make-userdata.sh — generate the Lightsail-safe user-data wrapper.
#
# Why this exists:
#   Lightsail prepends its own #!/bin/sh SSH-CA setup to whatever you pass as
#   --user-data and runs the combined script via dash. Our bootstrap.sh uses
#   bash-only features (`set -euo pipefail`, `[[ ]]`, etc.), so dash chokes and
#   cloud-init reports `scripts_user RuntimeError: Runparts: 1 failures`.
#
#   The fix: wrap bootstrap.sh content inside a POSIX-safe shim that dumps it
#   to disk via a quoted heredoc and execs bash on the result. The shim parses
#   cleanly in dash; bash takes over before any bash-only syntax runs.
#
# Usage:
#   ./scripts/make-userdata.sh
#   aws lightsail create-instances --user-data file://userdata.sh ...
#
# The output (userdata.sh) is gitignored — it is a build artifact regenerated
# from bootstrap.sh on demand.

set -e

# Resolve repo root from script location.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
SRC="${REPO_ROOT}/bootstrap.sh"
OUT="${REPO_ROOT}/userdata.sh"
MARKER="BOOTSTRAP_PAYLOAD_END_MARKER"
LIGHTSAIL_USER_DATA_LIMIT=16384

if [ ! -f "$SRC" ]; then
    printf 'ERROR: %s not found\n' "$SRC" >&2
    exit 1
fi

# Defensive: refuse to overwrite if bootstrap.sh contains a literal line
# matching our heredoc terminator (would prematurely close the outer heredoc).
if grep -q "^${MARKER}\$" "$SRC"; then
    printf 'ERROR: %s contains a line matching heredoc marker %s\n' "$SRC" "$MARKER" >&2
    printf '       Pick a different MARKER in scripts/make-userdata.sh.\n' >&2
    exit 1
fi

{
    echo '#!/bin/sh'
    echo '# AUTO-GENERATED by scripts/make-userdata.sh from bootstrap.sh.'
    echo '# DO NOT EDIT — edit bootstrap.sh and re-run the generator.'
    echo '#'
    echo '# Dash-safe wrapper for Lightsail user-data. Lightsail prepends its'
    echo '# own #!/bin/sh SSH-CA setup, so this whole file must parse in dash.'
    echo '# We dump bootstrap.sh to disk via a quoted heredoc (no expansion)'
    echo '# and exec bash on the result.'
    echo
    printf "cat > /root/jinx-bootstrap.sh <<'%s'\n" "$MARKER"
    cat "$SRC"
    echo "$MARKER"
    echo 'chmod +x /root/jinx-bootstrap.sh'
    echo 'exec bash /root/jinx-bootstrap.sh'
} > "$OUT"

SIZE=$(wc -c < "$OUT")
printf 'Generated %s (%s bytes)\n' "$OUT" "$SIZE"

if [ "$SIZE" -gt "$LIGHTSAIL_USER_DATA_LIMIT" ]; then
    printf 'ERROR: %s is %s bytes, exceeds Lightsail user-data limit of %s.\n' \
        "$OUT" "$SIZE" "$LIGHTSAIL_USER_DATA_LIMIT" >&2
    printf '       Trim bootstrap.sh or split into a fetch-from-URL pattern.\n' >&2
    exit 1
fi
